formatter: markdown table
output:
  file: README.md
  mode: replace

content: |-
  # Terraform templates for Google Cloud log export to Splunk
  
  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Requirements }}

  {{ include "README.template.md"}}

sort:
  enabled: true
  by: required
settings:
  indent: 4
  escape: false
  default: false
  required: false
  type: true